# Generated by Django 4.1.3 on 2022-12-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('adrs', models.TextField()),
                ('city', models.CharField(max_length=20)),
                ('contact', models.BigIntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('pasword', models.CharField(max_length=50)),
            ],
        ),
    ]
