# Generated by Django 4.1.3 on 2022-12-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('aurthor', models.CharField(max_length=50)),
                ('add_date', models.DateTimeField()),
                ('edition', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('number', models.BigIntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('message', models.CharField(max_length=70)),
            ],
        ),
    ]
