# Generated by Django 4.1.3 on 2022-12-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0003_rename_contact_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=30)),
                ('book_name', models.CharField(max_length=20)),
                ('contact', models.BigIntegerField()),
                ('issue_date', models.DateTimeField()),
                ('submit_date', models.DateTimeField()),
                ('fine', models.IntegerField()),
            ],
        ),
    ]
