# Generated by Django 4.1.3 on 2022-12-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0004_book_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_issue',
            name='fine',
        ),
        migrations.AlterField(
            model_name='book_issue',
            name='s_name',
            field=models.CharField(max_length=50),
        ),
    ]
