# Generated by Django 4.1.3 on 2022-12-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0005_remove_book_issue_fine_alter_book_issue_s_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_issue',
            name='issue_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='book_issue',
            name='submit_date',
            field=models.DateField(),
        ),
    ]
